### ISSUE TITLE
Reproduced Result

### ISSUE THREAD

**Issue by VectorYoung** [JiahuiYu/slimmable_networks#14]
Hi @JiahuiYu 

Thanks to your help, I have reproduced the US-MobileNet v1 at width [0.25, 1.0]. Could you please report the accuracy of US-MobileNet v1 at width [0.05, 1.0]? Since the exact accuracy is not given in the paper, just a graph. Thanks.

**Comment by JiahuiYu** [comment]
Great to hear that!

For US-MobileNet v1 at width [0.05, 1.0], here is the exact performance:

| Networks | 0.05 | 0.15 | 0.25 | 0.35 | 0.45 | 0.55 | 0.65 | 0.75 | 0.85 | 1.0 |
| - | - | - | - | - | - | - | - | - | - | - |
| lower bound 0.05 | 79.4% | 66.2% | 54.8% | 44.7% | 39.3% | 35.6% | 32.8% | 31.0% | 29.8% | 28.4% |
| lower bound 0.35 | - | - | - | 38.0% | 36.1% | 34.0% | 31.9% | 30.5% | 29.6% | 28.4% |
