### ISSUE TITLE
Training Speed

### ISSUE THREAD

**Issue by VectorYoung** [JiahuiYu/slimmable_networks#17]
Hi Jiahui,
Have you tried to implement US-ResNet50? I am trying to do that but the training speed is very slow. It takes 200min for one epoch, on a server with 8 RTX 2080Ti. Could you please share your training time for US-ResNet50 and S-ResNet50?

**Comment by JiahuiYu** [comment]
Hi @VectorYoung 

Yes I do have trained US-ResNet50 model, and it will be released together with AutoSlim models.

For training, what's the GPU utilization on your side? It should be around 99% for all GPUs, otherwise you need to optimize your disk reading speed.

**Comment by VectorYoung** [comment]
Yes, the GPU utilization is only around 30%. Could you give some idea on how to optimize the reading speed? I basically follow your codes with datasets.ImageFolder.

**Comment by VectorYoung** [comment]
Hi @JiahuiYu , I try to train S-ResNet50 with the provided codes, and the GPU utilization is also around 30%.

**Comment by JiahuiYu** [comment]
There are several existing ways to speed up your data loading:

1. If you have large memory (let's say >400GB), building LMDB or HDF5 file and loading them into memory would help.
2. If you do not have large memory, you will need to put ImageNet data into fast disks like SSD.
3. If either way above does not work for you, you could still get some (limited) speedup by carefully building datasets into chunks (e.g., tf record, mxnet record io).

For my case, I have both 1 and 2. So the training is relatively fast.
