### ISSUE TITLE
Sliming Object detection models 

### ISSUE THREAD

**Issue by abhigoku10** [JiahuiYu/slimmable_networks#19]
@JiahuiYu  wonderful work on the slimmable network , i had few following queries 

1. can this be applied to the object detection models which are trained 
2.how much drop in accuracy can we expected after slimming the network 

Thanks in advance

**Comment by JiahuiYu** [comment]
Object detection results are already included in our paper. There is no drop in mAP for object detection, instead there is some improvement. Moreover, code is also released so please check it out.
