### ISSUE TITLE
USNet for Obeject Detection

### ISSUE THREAD

**Issue by VectorYoung** [JiahuiYu/slimmable_networks#21]
Hi @JiahuiYu , congratulations to your acceptance to ICCV19 ! In the USNet paper, you didn't do object detection. Have you ever tried to apply USNet to object detection? Is it better than S-Net or not?

**Comment by JiahuiYu** [comment]
@VectorYoung Thanks for your interest!

I have not ran experiments on object detection. But I am kind of confident that USNets also work on OD. One requirement is that we should not freeze BN during training.
