### ISSUE TITLE
width_mult = None  when training us-Net

### ISSUE THREAD

**Issue by lucaskyle** [JiahuiYu/slimmable_networks#28]
in USConv2d

self.width_mult = None

then in forward function:

    self.in_channels = make_divisible(self.in_channels_max * self.width_mult/ self.ratio[0]) * self.ratio[0]
    

int  * None ?
i got type error
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

**Comment by JiahuiYu** [comment]
@lucaskyle The `width_mult` is set here:

https://github.com/JiahuiYu/slimmable_networks/blob/d211f5bc5b88918a25bdda9b61cfc9a4936b2a62/train.py#L301-L303

**Comment by lucaskyle** [comment]
thanks a lot

**Comment by BcomedianC** [comment]
Hi @lucaskyle, did you fixed the error:# TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'?# I'm experiencing the same error and can't seem to get rid of it. Thank you!
