### ISSUE TITLE
us.mobilenet_v2  cifar

### ISSUE THREAD

**Issue by lucaskyle** [JiahuiYu/slimmable_networks#29]
in us.mobilenet_v2.py
self.block_setting = [
            # t, c, n, s
            [1, 16, 1, 1],
            [6, 24, 2, 2],
            [6, 32, 3, 2],
            [6, 64, 4, 2],
            [6, 96, 3, 1],
            [6, 160, 3, 2],
            [6, 320, 1, 1],
        ]
        if FLAGS.dataset == 'cifar10':
            self.block_setting[2] = [6, 24, 2, 1]

as far as i know 
    should let self.block_setting[1] = [6, 24, 2, 1] right?

**Comment by lucaskyle** [comment]
hey there:

i modified a little bit for traning cifar10.
so far i can train stage-1  slimmable mobilenet v1 and v2 on cifar10.
i also want to modify  stage-2  Universally Slimmable Networks code.
but there are some bugs or mistakes as i issued. 

here is the branch 
https://github.com/lucaskyle/slimmable_networks

i wander when you would release the stage-3 auto slim code.

thx!!!

**Comment by JiahuiYu** [comment]
I guess self.block_setting[2] = [6, 24, 2, 1] or self.block_setting[1] = [6, 24, 2, 1] are all correct. As there are no official MobileNets for cifar. Please stay tuned on the AutoSlim code. We are currently working on it.

**Comment by lucaskyle** [comment]
thx a lot

**Comment by wlguan** [comment]
Hi, @lucaskyle  What performance did you get for cifar10?

**Comment by lucaskyle** [comment]
> Hi, @lucaskyle What performance did you get for cifar10?

hey there,
the result on cifar10 was not that good.
i think it needs more further adjustment.
i just forked this project last year.
u may check my github.
*train_cifar10.py*
