### ISSUE TITLE
Is num_sample_training=2 enough for training ?

### ISSUE THREAD

**Issue by bhheo** [JiahuiYu/slimmable_networks#31]
Hi

Thank you for release code. It is very useful.
I'm trying to reproduce performance of USNet.
As I know in USNet paper, you adopt n=4 for training which means num_sample_training is 4 
But, in your code, I found that your setting number is 2.
https://github.com/JiahuiYu/slimmable_networks/blob/d211f5bc5b88918a25bdda9b61cfc9a4936b2a62/apps/us_mobilenet_v2_train_val.yml#L54

Is this because 2 is enough for good performance ?
or 
Should I change this to 4 to reproduce performance of paper ?

**Comment by JiahuiYu** [comment]
Hi, thanks for your interest. In fact, here the number of samples of training means that except the smallest and biggest, how many more samples to train. So setting it to 2 means there are totally 4 iterations. 

https://github.com/JiahuiYu/slimmable_networks/blob/master/train.py#L412

**Comment by bhheo** [comment]
Thank you for your kind answer.

I think it might be something like you said.
But, in that line, you put `-2` to ```FLAGS.num_sample_training```
Here,
https://github.com/JiahuiYu/slimmable_networks/blob/d211f5bc5b88918a25bdda9b61cfc9a4936b2a62/train.py#L412

Is it a typo ?
Because of `-2`, this line gonna be `for _ in range(0):` which doesn't make iteration.

**Comment by JiahuiYu** [comment]
@bhheo Thanks for catching this error. Yes I think it is a typo. Before code release, I cleaned up the code which may introduce this typo.
