### ISSUE TITLE
Why bn layers do not have weight_decay?

### ISSUE THREAD

**Issue by leoozy** [JiahuiYu/slimmable_networks#33]
`    if FLAGS.optimizer == 'sgd':
        # all depthwise convolution (N, 1, x, x) has no weight decay
        # weight decay only on normal conv and fc
        model_params = []
        for name, params in model.named_parameters():
            ps = list(params.size())
            if len(ps) == 4 and ps[1] != 1:
                weight_decay = FLAGS.weight_decay
            elif len(ps) == 2:
                weight_decay = FLAGS.weight_decay
            else:
                pdb.set_trace()
                weight_decay = 0`

Hello, in your code here, you set the weight_decay for bn layers 0. But in your paper "slimmable_networks" you said nothing about it. Could you please tell me whether it is a bug or the weight_decay for bn should be 0

**Comment by JiahuiYu** [comment]
#15
