### ISSUE TITLE
Size mismatch when loading us_mobilenet_v2_calibrated.pt

### ISSUE THREAD

**Issue by pawopawo** [JiahuiYu/slimmable_networks#34]
thanks for your nice work~

When launching `python3 train.py app:apps/us_mobilenet_v2_train_val.yml` with logs/us_mobilenet_v2_calibrated.pt downloaded, size mismatch errors for all the running_mean and running_var of batchnorm

**Comment by lyn0102** [comment]
> thanks for your nice work~
> 
> When launching `python3 train.py app:apps/us_mobilenet_v2_train_val.yml` with logs/us_mobilenet_v2_calibrated.pt downloaded, size mismatch errors for all the running_mean and running_var of batchnorm

I also encountered this problem, did you solve this problem？~

**Comment by changlin31** [comment]
Hi, @pawopawo @lyn0102 
I encountered the same problem. This is caused by loading `latest_checkpoint.pt`  in your log dir. To solve this, try:
remove the unintended checkpoint:   `rm -f ./logs/latest_checkpoint.pt`
or comment out `line 582 - 595` in `train.py`

**Comment by lyn0102** [comment]
> Hi, @pawopawo @lyn0102
> I encountered the same problem. This is caused by loading `latest_checkpoint.pt` in your log dir. To solve this, try:
> remove the unintended checkpoint: `rm -f ./logs/latest_checkpoint.pt`
> or comment out `line 582 - 595` in `train.py`

It works，thx！
