### ISSUE TITLE
model profiling

### ISSUE THREAD

**Issue by lyn0102** [JiahuiYu/slimmable_networks#37]
Hello! I compared the results of statistical FLOPs and parameters in your code with the results in the thop tool, and found that there are some differences. I guess the reason is that you did not count the FLOPs and parameters of the bn layer? Looking forward to your answer, thank you!

**Comment by JiahuiYu** [comment]
I think all papers do not include BN as they can be fused during inference.

**Comment by lyn0102** [comment]
Thank you for your reply :D

**Comment by abhishekaich27** [comment]
Hi @JiahuiYu, are you calculating MACs or Flops? The code says "n_macs". 

Asking to be sure and make necessary changes.
