### ISSUE TITLE
Using Cifar-100 to train slimmable_networks

### ISSUE THREAD

**Issue by BcomedianC** [JiahuiYu/slimmable_networks#39]
Hi Jiahui! This is Bruce.
I'm new to this field and my mentor asked me to train and test slimmable_networks using Cifar-100 dataset. I just want to know is it possible to change imagenet dataset to Cifar-100? I've tried simply change the dataset dir to Cifar-100 but it seems more actions are required. 
Thank you very much!
PS Have been following your papers including the recent released Big-NAS, they are really interesting and insightful.

**Comment by JiahuiYu** [comment]
@BcomedianC Hi,

Yes it is possible to run cifar-100 -- I have an internal version of code that supports cifar100. You will need to understand the code and modify these functions: https://github.com/JiahuiYu/slimmable_networks/blob/4bb2a623f02a183fe08a5b7415338f148f46b363/train.py#L43-L114
