### ISSUE TITLE
Run the experiment with distributed mode

### ISSUE THREAD

**Issue by hwang595** [JiahuiYu/slimmable_networks#42]
Hi @JiahuiYu, thanks a lot for releasing the code for your awesome work! I'm inspired a lot by reading through your implementation.

I have one quick question about running the [slimmable ResNet-50 experiment](https://github.com/JiahuiYu/slimmable_networks/blob/master/apps/s_resnet50_train_val.yml) using `distributed` mode. In the current configuration file, it triggers [this line](https://github.com/JiahuiYu/slimmable_networks/blob/master/train.py#L39) by default. However, I have a server with 16 GPUs where using `DataParallel` is not efficient. How can I enable the training with `distributed` or `distributed_all_reduce` e.g. as implemented [here](https://github.com/JiahuiYu/slimmable_networks/blob/master/train.py#L30-L37)? 

Thanks a lot in advance.

Best,
Hongyi

**Comment by JiahuiYu** [comment]
Hi Hongyi,

Just adding `distributed: True` in config file and you should be ready to run.
