### ISSUE TITLE
memory increasing during testing

### ISSUE THREAD

**Issue by octavianmm** [JiahuiYu/slimmable_networks#43]
Hi,
I'm running the slimmable code in test mode (s-MobileNet v1) on a NVIDIA Jetson Nano and after the testing phase starts the occupied system memory keeps increasing until eventually the testing crashes with the message "Killed.". 
I added a 6GB swap in addition to the 4GB system memory, however after taking up approx 4-5GB it gets killed and the dmesg shows that it tried to access a large amount of memory (~11GB).
Any ideas? Is this very high memory consumption normal?

Thanks

**Comment by JiahuiYu** [comment]
Hey, I think it's normal to have memory overflow. What you can try is:

1. smaller batch size;
2. other NVIDIA GPUs;

Jetson Nano should be enough for inference tho.
